boat:
    model: 2025 Granocean W-60
    name: M/V PIKORUA
    house_battery_capacity_ah: 1440
anchor:
    bow_roller_height_m: 1.5
    chain_size_mm: 12
    chain_onboard_m: 150
    hull_type: power_cat
    windage_area_m2: 35
signalk:
    address: 100.103.214.1
    port: 3000
units: metric
ui:
    tank_labels:
        blackWater.1: PORT
        blackWater.6: STBD
        freshWater.0: PORT
        freshWater.3: STBD
        fuel.2: PORT FWD
        fuel.4: PORT AFT
        fuel.5: STBD FWD
        fuel.7: STBD AFT
    vessel_state_refresh_seconds: 10
